// PDashboard
// Source: kliques-prototype.jsx (v4 — Apple Health gradient + card UI)

function PDashboard({go,onMenu}){const stats=[{l:"Today",v:"4",s:"bookings"},{l:"This week",v:"$1,240",s:"+18%"}];const sched=[{n:"Sarah M.",svc:"Vocal Lesson",t:"10:30 AM",i:"SM"},{n:"Kai T.",svc:"Performance Coaching",t:"12:00 PM",i:"KT"},{n:"Lisa R.",svc:"Group Class",t:"2:00 PM",i:"LR"},{n:"David P.",svc:"Song Arrangement",t:"4:30 PM",i:"DP"}];return(<div style={{height:"100%",background:t.bg,overflowY:"auto",display:"flex",flexDirection:"column"}}><GradientHeader onMenu={onMenu} right={<div style={{display:"flex",gap:"8px",alignItems:"center"}}><button onClick={()=>go("p_alerts")} style={{width:"36px",height:"36px",borderRadius:"50%",background:"rgba(255,255,255,0.2)",backdropFilter:"blur(10px)",border:"none",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",position:"relative"}}><svg width="18" height="18" fill="none" stroke="#fff" strokeWidth="1.5" viewBox="0 0 24 24"><path d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" strokeLinecap="round" strokeLinejoin="round"/></svg><div style={{position:"absolute",top:"4px",right:"4px",width:"8px",height:"8px",borderRadius:"50%",background:"#fff",border:"2px solid "+t.accent}}/></button><Avatar initials="AW" size={36}/></div>}>
    <p style={{fontFamily:f,fontSize:"14px",color:"rgba(255,255,255,0.7)",margin:"12px 0 2px"}}>Wednesday, Mar 19</p>
    <h1 style={{fontFamily:f,fontSize:"28px",fontWeight:700,color:"#fff",margin:"0 0 16px"}}>Hi, Anny</h1>
    <div style={{display:"flex",gap:"10px"}}>{stats.map(s=><div key={s.l} style={{flex:1,padding:"14px 12px",borderRadius:"12px",background:"rgba(255,255,255,0.2)",backdropFilter:"blur(10px)"}}><p style={{fontFamily:f,fontSize:"12px",color:"rgba(255,255,255,0.7)",margin:"0 0 6px"}}>{s.l}</p><p style={{fontFamily:f,fontSize:"22px",fontWeight:700,color:"#fff",margin:"0 0 2px"}}>{s.v}</p><p style={{fontFamily:f,fontSize:"12px",color:"rgba(255,255,255,0.9)",fontWeight:600,margin:0}}>{s.s}</p></div>)}</div>
  </GradientHeader>
  <div style={{padding:"32px 16px 0",flex:1,display:"flex",flexDirection:"column"}}>
    <Card onClick={()=>go("p_bookings")} style={{display:"flex",alignItems:"center",gap:"12px",background:t.accentLight,cursor:"pointer"}}><div style={{width:"36px",height:"36px",borderRadius:"10px",background:t.accent,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><span style={{color:"#fff",fontFamily:f,fontSize:"16px",fontWeight:700}}>3</span></div><div><p style={{fontFamily:f,fontSize:"15px",fontWeight:600,color:t.fg,margin:0}}>Pending booking requests</p><p style={{fontFamily:f,fontSize:"13px",color:t.muted,margin:"2px 0 0"}}>Tap to review and accept</p></div></Card>
    <p style={{fontFamily:f,fontSize:"18px",fontWeight:700,color:t.fg,margin:"8px 4px 14px"}}>Today's schedule</p>
    {sched.map(u=><Card key={u.n} onClick={()=>go("p_appt_detail")} style={{display:"flex",alignItems:"center",gap:"14px",cursor:"pointer"}}><Avatar initials={u.i} size={44} bg={t.accentLight} color={t.accent}/><div style={{flex:1}}><p style={{fontFamily:f,fontSize:"16px",fontWeight:600,color:t.fg,margin:"0 0 2px"}}>{u.n}</p><p style={{fontFamily:f,fontSize:"14px",color:t.muted,margin:0}}>{u.svc}</p></div><span style={{fontFamily:f,fontSize:"14px",fontWeight:600,color:t.fg}}>{u.t}</span></Card>)}
  <Footer/></div></div>)}
